name: pixel_art_puzzle

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  firebase_core: ^1.13.1
  lottie: ^1.2.2
  pixabay_picker: ^1.0.6
  image: ^3.1.1
  file_picker: ^4.4.0
  rxdart: ^0.27.3
  streaming_shared_preferences: ^2.0.0
  glassmorphism: ^3.0.0
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
    - assets/images/difficulty/
