// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoo-4HZGMmy8G4Ns2N4X_DjNEHqPJD6k',
    appId: '1:972766593370:web:820a4aa4d0ef32d49bf363',
    messagingSenderId: '972766593370',
    projectId: 'pixel-art-puzzle-a1e13',
    authDomain: 'pixel-art-puzzle-a1e13.firebaseapp.com',
    storageBucket: 'pixel-art-puzzle-a1e13.appspot.com',
    measurementId: 'G-6ZFRTLVNYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ8v-iw9EyBWwhH34q8x_EUE206F52wos',
    appId: '1:972766593370:android:1fdcbd286c5f98fc9bf363',
    messagingSenderId: '972766593370',
    projectId: 'pixel-art-puzzle-a1e13',
    storageBucket: 'pixel-art-puzzle-a1e13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydYaEmpFnffsGgZPmqI_Nv0--uquRiUo',
    appId: '1:972766593370:ios:919fde42a5678e0d9bf363',
    messagingSenderId: '972766593370',
    projectId: 'pixel-art-puzzle-a1e13',
    storageBucket: 'pixel-art-puzzle-a1e13.appspot.com',
    iosClientId:
        '972766593370-3din7t2blelejikens9l02cdptlomn2r.apps.googleusercontent.com',
    iosBundleId: 'studio.happycode.pixelArtPuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydYaEmpFnffsGgZPmqI_Nv0--uquRiUo',
    appId: '1:972766593370:ios:919fde42a5678e0d9bf363',
    messagingSenderId: '972766593370',
    projectId: 'pixel-art-puzzle-a1e13',
    storageBucket: 'pixel-art-puzzle-a1e13.appspot.com',
    iosClientId:
        '972766593370-3din7t2blelejikens9l02cdptlomn2r.apps.googleusercontent.com',
    iosBundleId: 'studio.happycode.pixelArtPuzzle',
  );
}
